import { createHash } from "node:crypto"
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

export const GENERATED_MARKER = "// Generated by next-with-text"

// Live dev servers register here so a concurrent `next build` doesn't delete
// the route source they compile from. It lives in the OS temp dir keyed by
// project path: nothing about it belongs in the user's tree, and `next dev`
// clears .next at startup, which would take an in-project lock with it.
function lockDir(dir: string): string {
  const key = createHash("sha256").update(dir).digest("hex").slice(0, 12)
  return join(tmpdir(), `next-with-text-${key}`)
}

// A dev server claims the generated route for as long as it runs. One file per
// pid, so several dev servers can hold it at once and a crashed one leaves
// nothing that outlives its pid.
export function claimGeneratedRoute(dir: string): void {
  try {
    mkdirSync(lockDir(dir), { recursive: true })
    writeFileSync(join(lockDir(dir), String(process.pid)), "")
  } catch {
    // no lock is only a problem when another process races us — degraded, not broken
  }
}

export function releaseGeneratedRoute(dir: string): void {
  try {
    rmSync(join(lockDir(dir), String(process.pid)), { force: true })
  } catch {
    // the sweep below reclaims it once this pid is gone
  }
}

// Any live claim blocks deletion; dead pids are swept so a crashed dev server
// can't pin the route forever.
function claimed(dir: string): boolean {
  try {
    let live = false
    for (const entry of readdirSync(lockDir(dir))) {
      const pid = Number(entry)
      if (!Number.isInteger(pid) || pid <= 0) {
        continue
      }
      try {
        process.kill(pid, 0) // signal 0 only tests for existence
        live = true
      } catch {
        rmSync(join(lockDir(dir), entry), { force: true })
      }
    }
    return live
  } catch {
    return false
  }
}

// The codegen'd app/%5Fllms route is scaffolding: the build compiles it into
// .next (which is what start/serverless serve) and dev compiles it live, so
// once the owning process exits the source folder is dead weight — delete it
// rather than leave generated noise in the user's app tree.
export function cleanupGeneratedRoute(dir: string): void {
  const appDir = ["src/app", "app"].map((d) => join(dir, d)).find(existsSync)
  if (!appDir || claimed(dir)) {
    return
  }
  const routeDir = join(appDir, "%5Fllms")
  const routeFile = join(routeDir, "[...path]", "route.ts")
  try {
    // only ever delete a file we generated; a user's own route at this path
    // (no marker) is left alone, as is anything else they placed in the folder
    if (
      !(
        existsSync(routeFile) &&
        readFileSync(routeFile, "utf8").startsWith(GENERATED_MARKER)
      )
    ) {
      return
    }
    rmSync(routeFile, { force: true })
    for (const parent of [join(routeDir, "[...path]"), routeDir]) {
      try {
        rmdirSync(parent) // non-recursive: refuses if the user put files here
      } catch {
        break
      }
    }
  } catch {
    // read-only filesystem — nothing was generated there either
    return
  }
  // Next's typegen validator holds a `typeof import(...)` of the deleted file;
  // tsconfig includes .next/types and .next/dev/types, so leaving it dangling
  // trades folder noise for a TS2307 in the user's editor. routes.d.ts only
  // holds string literal types — nothing dangles there.
  for (const validator of [
    join(dir, ".next", "types", "validator.ts"),
    join(dir, ".next", "dev", "types", "validator.ts"),
  ]) {
    scrubValidator(validator)
  }
}

// Removes our route's validation block: `// Validate …%5Fllms…` through the
// closing `}`. If Next ever reshapes this file the regex just stops matching —
// worst case is one stale TS error that the next build regenerates away.
function scrubValidator(path: string): void {
  try {
    if (!existsSync(path)) {
      return
    }
    const source = readFileSync(path, "utf8")
    const scrubbed = source.replace(
      /\/\/ Validate [^\n]*%5Fllms[^\n]*\n\{[\s\S]*?\n\}\n*/g,
      ""
    )
    if (scrubbed !== source) {
      writeFileSync(path, scrubbed)
    }
  } catch {
    // best-effort — same degraded-not-broken story as above
  }
}
